filter:
    excluded_paths:
        - bin/*
        - tests/*
        - data/*

checks:
    php:
        code_rating: true
        duplication: true

coding_style:
    php: {  }

tools:
    external_code_coverage:
        timeout: 1200
        runs: 2
